<template>
  <div id="bg" class="body">
    <div class="bounce-in-top">
      <div class="register">
        <div>
          <h1>Death Dice</h1>
        </div>
        <div class="container">
          <form>
            <div class="form-group">
              <label for="usr">Guest</label>
              <input v-model="name" type="text" class="form-control" id="usr">
              <br>
            </div><button @click="register" type="button" class="btn btn-outline-danger">Let's Play !!</button>
          </form>
        </div>
      </div>
    </div>
  </div>

</template>

<script>
  export default {
    name: 'register',
    data: function () {
      return {
        name: ''
      }
    },
    methods: {
      register() {
        this.$store.dispatch('register', this.name)
        this.name = ''
        this.$router.push('lobby')
      }
    }
  }
</script>

<style>
  #bg {
    background-image: url("../assets/logo0.jpg");
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
    height: 100%;
  }
  .form-control {
      display: block;
      width: 30%;
      padding: .375rem .75rem;
      font-size: 18px;
      line-height: 1.5;
      color: #495057;
      background-color: #fff;
      background-clip: padding-box;
      border: 1px solid #ced4da;
      border-radius: 30px;
      transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
  }
  h1 {
    font-family: 'Permanent Marker', cursive;
    font-size: 45px;
    font-weight: 300;
    margin-bottom: 25px;
  }

  label {
    font-family: 'Eater', cursive;
  }

  .register {
    height: 100%;
    margin-top: 20px;
    padding: 200px;
  }

  input {
    width: 30%;
    margin: auto;
    text-align: center;
  }

  .bounce-in-top {
    -webkit-animation: bounce-in-top 1.1s both;
    animation: bounce-in-top 1.1s both;
  }

  .btn-outline-danger {
    font-size: 20px;
  }

  /* ----------------------------------------------
 * Generated by Animista on 2018-5-17 21:44:2
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation bounce-in-top
 * ----------------------------------------
 */

  @-webkit-keyframes bounce-in-top {
    0% {
      -webkit-transform: translateY(-500px);
      transform: translateY(-500px);
      -webkit-animation-timing-function: ease-in;
      animation-timing-function: ease-in;
      opacity: 0;
    }
    38% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
      opacity: 1;
    }
    55% {
      -webkit-transform: translateY(-65px);
      transform: translateY(-65px);
      -webkit-animation-timing-function: ease-in;
      animation-timing-function: ease-in;
    }
    72% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
    }
    81% {
      -webkit-transform: translateY(-28px);
      transform: translateY(-28px);
      -webkit-animation-timing-function: ease-in;
    }
    90% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
    }
    95% {
      -webkit-transform: translateY(-8px);
      transform: translateY(-8px);
      -webkit-animation-timing-function: ease-in;
      animation-timing-function: ease-in;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
    }
  }

  @keyframes bounce-in-top {
    0% {
      -webkit-transform: translateY(-500px);
      transform: translateY(-500px);
      -webkit-animation-timing-function: ease-in;
      animation-timing-function: ease-in;
      opacity: 0;
    }
    38% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
      opacity: 1;
    }
    55% {
      -webkit-transform: translateY(-65px);
      transform: translateY(-65px);
      -webkit-animation-timing-function: ease-in;
      animation-timing-function: ease-in;
    }
    72% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
    }
    81% {
      -webkit-transform: translateY(-28px);
      transform: translateY(-28px);
      -webkit-animation-timing-function: ease-in;
    }
    90% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
    }
    95% {
      -webkit-transform: translateY(-8px);
      transform: translateY(-8px);
      -webkit-animation-timing-function: ease-in;
      animation-timing-function: ease-in;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
    }
  }
</style>