<template>
  <div class="body">
    <div class="bounce-in-top">
      <div class="register">
        <div>
          <h1 class="mb-20">Death Dice</h1>
        </div>
        <div class="container">
          <form>
            <div class="form-group">
              <label for="usr">Guest</label>
              <input v-model="name" type="text" class="form-control" id="usr">
              <br>
            </div><button @click="register" type="button" class="btn btn-outline-danger">Let's Rock Baby !!</button>
          </form>
        </div>
      </div>
    </div>
  </div>

</template>

<script>
  export default {
    name: 'register',
    data: function () {
      return {
        name: ''
      }
    },
    methods: {
      register() {
        this.$store.dispatch('register', this.name)
        this.name = ''
        this.$router.push('lobby')
      }
    }
  }
</script>

<style>
  body {
    background-image: url('https://00e9e64bac025f2adb837b3127f25d55efe02c82e94c81b348-apidata.googleusercontent.com/download/storage/v1/b/soc-med.unguhiu.com/o/bg_dice_death.jpg?qk=AD5uMEs5aCTCf23xfvdObd3Bi70hdoFteWPnEXb_eC2_lwmOBX-dcYLc23pgHz2m4uXXBhjykd1rEU-o-G5L8-lSERcYAtTIX7SUQNt93TwKzklRm9dbVUYLCvxcesS2dbe2djnS7ACVFe92LM8sZigJO3tno2ZtcSeujH2WdYNNdpXQLWXeu93aUeP2dZlmTTj8hREaUmAb8HRBCZxzXMubkSwiWSbYxMJr0nvqMliuSbrcgYvkEcSJtsw_a7xCSbz1it-gCHU7Z7uM_8TI-db8kaRVEb7q0BzU1ieICNYou94YqEoyn1olCxVLRKKjtE2wUt10YjMX47y37mo_mFuoNJutAylSiNzW1cINwrc5A8qxKOpBReSzjFyNxIz1g1hRino8ngPQEgwq0KEIOdhUYyUG5jhhgZF83xYmLAq8AD-B6IrKeoDdznGvxWe2obEECnXT7LUXZQdquMt-fYUfm5pH5eKiLM_-Jwwzl02ciD6mD1hnp-KMUkFTqATdRG--tpxeE-adOVnU97yWAxY74_z2Amp9615xLhEOhL9ycLars6hYcil47-hpK8ZERt0heF0VcyNJScQx1ctPh6GyF3gr9Y76dbTPadyYHAdmJAGd3h7MQFSD43wbsgxq0NlKvZ6aqLEwI0neCti7sxqvOgf29IdYR3nOGycKfJlPNukt4wyb6QSIApG8A3Fcq5FDqhDhYw0Q89Te3aRduBES4L7v-MNnmms5337FOsKMx15lUOr8CjU');
    background-repeat: no-repeat;
    background-position: 0 0;
    background-size: cover;
  }
  .form-control {
      display: block;
      width: 30%;
      padding: .375rem .75rem;
      font-size: 1rem;
      line-height: 1.5;
      color: #495057;
      background-color: #fff;
      background-clip: padding-box;
      border: 1px solid #ced4da;
      border-radius: .25rem;
      transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
  }
  h1 {
    margin-bottom: 25px;
  }

  .register {
    margin-top: 250px;
  }

  input {
    width: 30%;
    margin: auto;
    text-align: center;
  }

  .bounce-in-top {
    -webkit-animation: bounce-in-top 1.1s both;
    animation: bounce-in-top 1.1s both;
  }

  .btn-outline-danger {
    font-size: 20px;
  }

  /* ----------------------------------------------
 * Generated by Animista on 2018-5-17 21:44:2
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation bounce-in-top
 * ----------------------------------------
 */

  @-webkit-keyframes bounce-in-top {
    0% {
      -webkit-transform: translateY(-500px);
      transform: translateY(-500px);
      -webkit-animation-timing-function: ease-in;
      animation-timing-function: ease-in;
      opacity: 0;
    }
    38% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
      opacity: 1;
    }
    55% {
      -webkit-transform: translateY(-65px);
      transform: translateY(-65px);
      -webkit-animation-timing-function: ease-in;
      animation-timing-function: ease-in;
    }
    72% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
    }
    81% {
      -webkit-transform: translateY(-28px);
      transform: translateY(-28px);
      -webkit-animation-timing-function: ease-in;
    }
    90% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
    }
    95% {
      -webkit-transform: translateY(-8px);
      transform: translateY(-8px);
      -webkit-animation-timing-function: ease-in;
      animation-timing-function: ease-in;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
    }
  }

  @keyframes bounce-in-top {
    0% {
      -webkit-transform: translateY(-500px);
      transform: translateY(-500px);
      -webkit-animation-timing-function: ease-in;
      animation-timing-function: ease-in;
      opacity: 0;
    }
    38% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
      opacity: 1;
    }
    55% {
      -webkit-transform: translateY(-65px);
      transform: translateY(-65px);
      -webkit-animation-timing-function: ease-in;
      animation-timing-function: ease-in;
    }
    72% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
    }
    81% {
      -webkit-transform: translateY(-28px);
      transform: translateY(-28px);
      -webkit-animation-timing-function: ease-in;
    }
    90% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
    }
    95% {
      -webkit-transform: translateY(-8px);
      transform: translateY(-8px);
      -webkit-animation-timing-function: ease-in;
      animation-timing-function: ease-in;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      -webkit-animation-timing-function: ease-out;
      animation-timing-function: ease-out;
    }
  }
</style>